### ISSUE TITLE
The illustration of nav-graph and R2R env

### ISSUE THREAD

**Issue by PygmalionChen** [zhangybzbo/EnvBiasVLN#2]
I've read your novelty paper "Diagnosing the Environment Bias in Vision-and-Language Navigation". Could you give me some advice about illustrating the navigation graph like Figure1 and Figure3 in your paper?

**Comment by zhangybzbo** [comment]
Hi @PygmalionChen, thanks for being interested in our work!

You may find the python library [networkx](https://github.com/networkx/networkx) useful. It is the library we used to generate the graph in Figure3.

Good luck!
